# Generated by Django 5.1.6 on 2025-02-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='lifetime',
            field=models.BooleanField(default=True),
        ),
    ]
