# Generated by Django 5.1.6 on 2025-02-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_package_lifetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='lifetime',
            field=models.CharField(default='Lifetime', max_length=50),
        ),
    ]
