# Generated by Django 5.1.6 on 2025-02-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_alter_package_lifetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='lifetime',
            new_name='type',
        ),
    ]
