# Generated by Django 5.1.6 on 2025-02-10 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_status', models.CharField(choices=[('DM', 'Dormant'), ('AC', 'Active')], default='DM', max_length=2)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('gold_plan_active', models.BooleanField(default=False)),
                ('total_sent_transfers', models.IntegerField(default=0)),
                ('whatsapp_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_whatsapp_withdrawal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('earning_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('referral_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_withdrawn', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('referral_link', models.URLField(blank=True, max_length=255, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
