# Generated by Django 5.1 on 2025-02-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='app_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='deposit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='earning_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='gold_plan_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_sent_transfers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_whatsapp_withdrawal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='unique_referral',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_earnings',
            field=models.IntegerField(default=0),
        ),
    ]
