# Generated by Django 5.1.6 on 2025-03-05 17:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_earning_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='earning_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100),
        ),
    ]
