# Generated by Django 5.1.6 on 2025-02-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_total_sent_transfers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unique_referral',
            field=models.CharField(blank=True, default='zenithachievers', max_length=20, null=True, unique=True),
        ),
    ]
