# Generated by Django 5.1.6 on 2025-02-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_unique_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unique_referral',
            field=models.CharField(blank=True, default='zenithachievers', max_length=20, null=True),
        ),
    ]
