# Generated by Django 5.1.6 on 2025-02-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_unique_referral_profile_invited_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='order_details',
        ),
    ]
