# Generated by Django 5.1.6 on 2025-02-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_profile_order_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='app_earnings',
            new_name='referral_earnings',
        ),
    ]
