# Generated by Django 5.1.6 on 2025-02-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_app_earnings_profile_referral_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_status',
            field=models.CharField(choices=[('DM', 'Dormant'), ('AC', 'Active')], default='DM', max_length=2),
        ),
    ]
