# Generated by Django 5.1.6 on 2025-02-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_whatsapp_withdrawal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
