# Generated by Django 5.1.6 on 2025-02-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profile_total_whatsapp_withdrawal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_sent_transfers',
            field=models.IntegerField(default=0),
        ),
    ]
