# Generated by Django 5.1.6 on 2025-02-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_image', models.ImageField(upload_to='landing_images')),
                ('landing_title', models.CharField(max_length=100)),
                ('landing_caption', models.CharField(max_length=100)),
                ('landing_btn_text', models.CharField(max_length=100)),
                ('landing_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials')),
                ('client_name', models.CharField(max_length=33)),
                ('testimonial_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_of_business', models.ImageField(blank=True, null=True, upload_to='webcms')),
                ('name_of_business', models.CharField(max_length=33)),
                ('phone_of_business', models.CharField(max_length=11)),
                ('address_of_business', models.CharField(max_length=100)),
                ('phrase_of_business', models.CharField(max_length=500)),
                ('email_of_business', models.CharField(max_length=33)),
                ('maplink', models.CharField(blank=True, max_length=3000)),
            ],
        ),
    ]
