# Generated by Django 5.1.6 on 2025-02-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='receiver',
            field=models.CharField(max_length=255),
        ),
    ]
