# Generated by Django 5.1.6 on 2025-02-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transfer_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='description',
        ),
    ]
