# Generated by Django 5.1.6 on 2025-02-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_transfer_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-created']},
        ),
    ]
