# Generated by Django 5.1.6 on 2025-02-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='loan_request_reference_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
