# Generated by Django 5.1.6 on 2025-02-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappwithdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappscreenshot',
            name='phone_number',
        ),
    ]
